export { default as Navbar } from "./components/Navbar/Navbar"
export { default as Hero } from "./components/Hero/Hero"
export { default as Services } from "./components/Services/Services"
export { default as Banner } from "./components/Banner/Banner"
export { default as Banner2 } from "./components/Banner/Banner2"
export { default as Footer } from "./components/Footer/Footer"